# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('pickup_lat', models.CharField(max_length=12)),
                ('pickup_long', models.CharField(max_length=12)),
                ('dropoff_lat', models.CharField(max_length=12)),
                ('dropoff_long', models.CharField(max_length=12)),
                ('base', models.CharField(max_length=6)),
            ],
        ),
    ]
