# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injestor', '0002_auto_20160806_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='dropoff_lat',
            field=models.DecimalField(db_index=True, decimal_places=12, max_digits=15),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dropoff_long',
            field=models.DecimalField(db_index=True, decimal_places=12, max_digits=15),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_lat',
            field=models.DecimalField(db_index=True, decimal_places=12, max_digits=15),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_long',
            field=models.DecimalField(db_index=True, decimal_places=12, max_digits=15),
        ),
    ]
